version: '2.1'
services:
  app:
    build: .
    command: npm run start:dev
    environment:
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=secret
    ports:
      - "8080:8080"
      - "5858:5858"
    links:
      - postgres
    volumes:
      - .:/app/
    network_mode: bridge

  postgres:
    image: postgres
    restart: always
    environment:
        - POSTGRES_DB=discovery
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d
    network_mode: bridge

